/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package peticionesdisco;

import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author ASUSTEC
 */
public class ScanNPasos extends javax.swing.JFrame {
DefaultTableModel modeloP;
int contadorP=1;
int presionado=0;
int contadorOrden=0;
    /** Creates new form ScanNPasos */
    public ScanNPasos() {
        initComponents();
        modeloP= new DefaultTableModel();
        modeloP.addColumn("ID");
         modeloP.addColumn("Localidad");
         modeloP.addColumn("Estado");
        tablaP.setModel(modeloP); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInicio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPeticion = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnAleatorio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaP = new javax.swing.JTable();
        btnEjecutar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Vaciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("SCAN-N-PASOS");

        jLabel2.setText("Numero de Pista (1-200)");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnAleatorio.setText("Aleatorio");
        btnAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAleatorioActionPerformed(evt);
            }
        });

        tablaP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "Peticion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaP);

        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        jLabel3.setText("Inicio");

        jButton2.setText("Aleatorio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAleatorio))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtPeticion)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(119, 119, 119)
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEjecutar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnAleatorio)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnEjecutar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         txtInicio.setText("");
        txtInicio.setEditable(true);
        try{
            while(true){
                modeloP.removeRow(0);
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String []fila= new String[3];
        String nombre= "D"+contadorP;
        fila[0]= nombre;
        fila[1]= txtPeticion.getText();
        fila[2]= String.valueOf(contadorOrden);
        
        modeloP.addRow(fila);
        contadorP++;
        txtPeticion.setText("");
        txtPeticion.requestFocus();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAleatorioActionPerformed
        // TODO add your handling code here:
        int k= Integer.parseInt(JOptionPane.showInputDialog(null,"Numero de pistas que desea crear"));
        String []datos=new String[3];
        Random tamaño = new Random();
        for(int i=0;i<k;i++){
            datos[0] = "R"+String.valueOf(i+100);
            datos[1] = String.valueOf(1+tamaño.nextInt(200));
            datos[2] = String.valueOf(contadorOrden);
            modeloP.addRow(datos);
        }
    }//GEN-LAST:event_btnAleatorioActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        // TODO add your handling code here:
       int ultimo = 0;
        int inicio = Integer.parseInt(txtInicio.getText());
        String reporte = "Orden de numeros: ";
       int estadisticas[]= new int [tablaP.getRowCount()+1];
       estadisticas[0]=inicio;
        
        
        

        //Recoleccion de datos
        String datos[][] = new String[tablaP.getRowCount()][3];
        for (int i = 0; i < tablaP.getRowCount(); i++) {
            datos[i][0] = tablaP.getValueAt(i, 0).toString();
            datos[i][1] = tablaP.getValueAt(i, 1).toString();
            datos[i][2] = tablaP.getValueAt(i, 2).toString();
        }

        
        //Introduccion de datos para graficar    
        XYSeries series = new XYSeries("Disco Duro");
        int c = 1;
        series.add(0, inicio);
        for (int k = 0; k <= contadorOrden; k++) {
            //Primera Vuelta
            for (int i = inicio; i>0; i--) {
                for (int h = 0; h < tablaP.getRowCount(); h++) {
                    int n = Integer.parseInt(datos[h][1]);
                    int orden = Integer.parseInt(datos[h][2]);
                    if ((n == i)&&(orden==k)) {
                        reporte = reporte + n + ",";
                        series.add(c, n);
                        estadisticas[c]=n;
                        ultimo = n;
                        c++;

                    }
                }

            }//Fin de primera vuelta
            
            //Segunda vuelta
        for (int i = inicio+1; i <=200; i++) {
            for (int h = 0; h < tablaP.getRowCount(); h++) {
                int n = Integer.parseInt(datos[h][1]);
                int orden = Integer.parseInt(datos[h][2]);
                if ((n == i)&&(orden==k)) {
                    series.add(c, n);
                    estadisticas[c]=n;
                    reporte = reporte + n + ",";
                    ultimo = n;
                    c++;

                }
            }

        }//FIN DE ORDENAR LOS DATOS
        }

       

        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(series);

        JFreeChart chart = ChartFactory.createXYLineChart(
            "Peticiones", // Título
            "Movimientos", // Etiqueta Coordenada X
            "Pistas", // Etiqueta Coordenada Y
            dataset, // Datos
            PlotOrientation.VERTICAL,
            true,
            false,
            false
        );

        // Mostramos la grafica en pantalla
        ChartFrame frame = new ChartFrame("SCAN N Pasos", chart);
        frame.pack();
        frame.setVisible(true);

        
        int totalPistas=0;
        int pistas=0;
        int promedio=0;
        int varianza=0;
       for(int i=0; i<estadisticas.length-1;i++){
           totalPistas=totalPistas+Math.abs(estadisticas[i+1]-estadisticas[i]);
           
       }
       promedio= (totalPistas)/(estadisticas.length-1);
      for(int i=0; i<estadisticas.length-1;i++){
           pistas=Math.abs(estadisticas[i+1]-estadisticas[i]);
           varianza=varianza+(pistas-promedio)*(pistas-promedio);
       }
      varianza=varianza/(estadisticas.length-1);
       
        JOptionPane.showMessageDialog(null, "Casilla de inicio= " + inicio + "\n" + reporte + "\n"
        +"Pistas recorridas= "+totalPistas+"\nPromedio= "+promedio+"\nVarianza= "+varianza);
       
        contadorOrden++;
        
          
    }//GEN-LAST:event_btnEjecutarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Random tamaño = new Random();
        txtInicio.setText(String.valueOf(tamaño.nextInt(200)));
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScanNPasos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScanNPasos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScanNPasos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScanNPasos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScanNPasos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAleatorio;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaP;
    private javax.swing.JTextField txtInicio;
    private javax.swing.JTextField txtPeticion;
    // End of variables declaration//GEN-END:variables

}
