/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peticionesdisco;

import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author ASUSTEC
 */
public class ShortesFirst extends javax.swing.JFrame {
         DefaultTableModel modeloP;
int contadorP=1;
    /**
     * Creates new form ShortesFirst
     */
    public ShortesFirst() {
        initComponents();
         modeloP= new DefaultTableModel();
        modeloP.addColumn("ID");
         modeloP.addColumn("Localidad");
        tablaP.setModel(modeloP); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtInicio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPeticion = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnAleatorio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaP = new javax.swing.JTable();
        btnEjecutar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Inicio");

        jButton1.setText("Vaciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Shortest First");

        jLabel2.setText("Numero de Pista (1-200)");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnAleatorio.setText("Aleatorio");
        btnAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAleatorioActionPerformed(evt);
            }
        });

        tablaP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "Peticion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaP);

        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        jButton2.setText("Aleatorio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAleatorio))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtPeticion)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEjecutar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar)
                            .addComponent(btnAleatorio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(4, 4, 4)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEjecutar)
                    .addComponent(jButton1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         txtInicio.setText("");
        txtInicio.setEditable(true);
        try{
            while(true){
                modeloP.removeRow(0);
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String []fila= new String[2];
        String nombre= "D"+contadorP;
        fila[0]= nombre;
        fila[1]= txtPeticion.getText();

        modeloP.addRow(fila);
        contadorP++;
        txtPeticion.setText("");
        txtPeticion.requestFocus();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAleatorioActionPerformed
        // TODO add your handling code here:
        int k= Integer.parseInt(JOptionPane.showInputDialog(null,"Numero de pistas que desea crear"));
        String []datos=new String[2];
        Random tamaño = new Random();
        for(int i=0;i<k;i++){
            datos[0] = "R"+String.valueOf(i+100);
            datos[1] = String.valueOf(1+tamaño.nextInt(200));

            modeloP.addRow(datos);
        }
    }//GEN-LAST:event_btnAleatorioActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        // TODO add your handling code here:
       
        int inicio = Integer.parseInt(txtInicio.getText());
        String reporte = "Orden de numeros: ";
       int estadisticas[]= new int [tablaP.getRowCount()+1];
        //Recoleccion de datos
        int datos[] = new int[tablaP.getRowCount()];
        
        for (int i = 0; i < datos.length; i++) {
            datos[i] = Integer.parseInt(tablaP.getValueAt(i, 1).toString());
            
        }
          
    
    
       XYSeries series = new XYSeries("Disco Duro");
       int superior=0;
       int inferior=0;
        int banderasup=0;
        int posicion=Integer.parseInt(txtInicio.getText());
        int posicionBandera=0;
        int ultimo=0;
        int contador=0;
        
        while ((posicion > 0) && (posicion < 201)) {
            series.add(contador, posicion);
            estadisticas[contador] = posicion;
            
            ultimo=posicion;
            contador++;
            //CALCULAR SUPERIOR MAS CERCANO
            for (int sup = posicion; sup < 201; sup++) {
                for (int d = 0; d < datos.length; d++) {
                    if (datos[d] == sup) {
                        superior = datos[d];
                        sup = 201;
                        break;
                    }
                }
            }//Fin de superior mas cercano

            //CALCULAR INFERIOR MAS CERCANO
            for (int inf = posicion; inf > 0; inf--) {
                for (int d = 0; d < datos.length; d++) {
                    if (datos[d] == inf) {
                        inferior = datos[d];
                        inf = 0;
                        break;
                    }
                }

            }//FIN DE CALCULAR INFERIOR MAS CERCANO

            int restaSup = superior - posicion;
            int restaInf = posicion - inferior;

            if ((superior == 0) && (inferior == 0)) {

                posicion = 0;

            } else {

                if (superior == 0) {
                    posicion = inferior;
                    for (int i = 0; i < datos.length; i++) {
                        if (datos[i] == inferior) {
                            datos[i] = 0;
                            break;
                        }
                    }

                } else {
                    if (inferior == 0) {
                        posicion = superior;
                        for (int i = 0; i < datos.length; i++) {
                            if (datos[i] == superior) {
                                datos[i] = 0;
                                break;
                            }
                        }
                    } else {
                        if (restaSup < restaInf) {
                            posicion = superior;

                            for (int i = 0; i < datos.length; i++) {
                                if (datos[i] == superior) {
                                    datos[i] = 0;
                                    break;
                                }

                            }

                        } else {
                            posicion = inferior;

                            for (int i = 0; i < datos.length; i++) {
                                if (datos[i] == inferior) {
                                    datos[i] = 0;
                                    break;
                                }

                            }

                        }
                    }
                }
            }

            superior = 0;
            inferior = 0;
            
            if(posicion!=0){
            reporte = reporte + posicion + ",";
            }

        }
      XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(series);

        JFreeChart chart = ChartFactory.createXYLineChart(
                "Peticiones", // Título
                "Movimientos", // Etiqueta Coordenada X
                "Pistas", // Etiqueta Coordenada Y
                dataset, // Datos
                PlotOrientation.VERTICAL,
                true,
                false,
                false
        );

        // Mostramos la grafica en pantalla
        ChartFrame frame = new ChartFrame("Shortest Seek Time First", chart);
        frame.pack();
        frame.setVisible(true);
        
        int totalPistas=0;
        int pistas=0;
        int promedio=0;
        int varianza=0;
       for(int i=0; i<estadisticas.length-1;i++){
           totalPistas=totalPistas+Math.abs(estadisticas[i+1]-estadisticas[i]);
           
       }
       promedio= (totalPistas)/(estadisticas.length-1);
      for(int i=0; i<estadisticas.length-1;i++){
           pistas=Math.abs(estadisticas[i+1]-estadisticas[i]);
           varianza=varianza+(pistas-promedio)*(pistas-promedio);
       }
      varianza=varianza/(estadisticas.length-1);
       
        JOptionPane.showMessageDialog(null, "Casilla de inicio= " + inicio + "\n" + reporte + "\n"
        +"Pistas recorridas= "+totalPistas+"\nPromedio= "+promedio+"\nVarianza= "+varianza);
        txtInicio.setText(String.valueOf(ultimo));
        txtInicio.setEditable(false);
        try {
            while (true) {
                modeloP.removeRow(0);
            }
        } catch (Exception e) {

        }
        
    }//GEN-LAST:event_btnEjecutarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Random tamaño = new Random();
        txtInicio.setText(String.valueOf(tamaño.nextInt(200)));
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShortesFirst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShortesFirst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShortesFirst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShortesFirst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShortesFirst().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAleatorio;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaP;
    private javax.swing.JTextField txtInicio;
    private javax.swing.JTextField txtPeticion;
    // End of variables declaration//GEN-END:variables
}
